package kr.co.d_erp.domain;

import java.time.LocalDate;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import kr.co.d_erp.models.PasswordHandler;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "TB_USERMST",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_TB_USERMST_USER_ID", columnNames = {"USER_ID"}),
                @UniqueConstraint(name = "UQ_TB_USERMST_USER_E_MAIL", columnNames = {"USER_E_MAIL"}),
                @UniqueConstraint(name = "UQ_TB_USERMST_USER_TEL", columnNames = {"USER_TEL"}),
                @UniqueConstraint(name = "UQ_TB_USERMST_USER_HP", columnNames = {"USER_HP"})
        }
)
@DynamicInsert // insert 시 null이 아닌 필드만 포함 (DB default 값 활용)
@DynamicUpdate // update 시 변경된 필드만 포함
public class Usermst {
    
    // PasswordHandler는 Service 레이어에서 주입받아 사용
    @Transient
    private PasswordHandler passwordHandler;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Oracle의 GENERATED BY DEFAULT ON NULL AS IDENTITY 와 유사
    @Column(name = "USER_IDX")
    private Long userIdx;

    @Column(name = "USER_ID", length = 10, nullable = false)
    private String userId;

    @Column(name = "USER_PSWD", length = 100, nullable = false)
    private String userPswd; // 실제 사용 시 암호화 필요

    @Column(name = "USER_NM", length = 50, nullable = false)
    private String userNm;

    @Column(name = "USER_E_MAIL", length = 30, nullable = false)
    private String userEmail;

    @Column(name = "USER_TEL", length = 20, nullable = false)
    private String userTel;

    @Column(name = "USER_HP", length = 20, nullable = false)
    private String userHp;

    @Column(name = "USER_DEPT", length = 20, nullable = false)
    private String userDept;

    @Column(name = "USER_POSITION", length = 20, nullable = false)
    private String userPosition;

    @Column(name = "HIRE_DT", nullable = false)
    private LocalDate hireDt;

    @Column(name = "RETIRE_DT")
    private LocalDate retireDt;

    @Column(name = "USER_ROLE", length = 2, nullable = false, columnDefinition = "VARCHAR2(2) DEFAULT '01'")
    private String userRole; // CHECK 제약은 DB 레벨에서 적용, 필요시 @Pattern 등으로 Java 유효성 검사 추가

    @Column(name = "USER_STATUS", length = 2, nullable = false, columnDefinition = "VARCHAR2(2) DEFAULT '01'")
    private String userStatus; // CHECK 제약은 DB 레벨에서 적용

    // 편의를 위한 초기화 메서드 (USER_ROLE, USER_STATUS 기본값 설정)
    @PrePersist
    protected void onCreate() {
        if (this.userRole == null) {
            this.userRole = "01";
        }
        if (this.userStatus == null) {
            this.userStatus = "01";
        }
    }
    
    // ========== 비밀번호 관련 편의 메서드 (PasswordHandler 위임) ==========
    
    /**
     * PasswordHandler 설정 (Service에서 주입)
     */
    public void setPasswordHandler(PasswordHandler passwordHandler) {
        this.passwordHandler = passwordHandler;
    }
    
    /**
     * 비밀번호 설정 (자동 암호화)
     */
    public void setRawPassword(String rawPassword) {
        if (this.passwordHandler == null) {
            throw new IllegalStateException("PasswordHandler가 설정되지 않았습니다");
        }
        this.userPswd = passwordHandler.encode(rawPassword);
    }
    
    /**
     * 비밀번호 검증
     */
    public boolean checkPassword(String rawPassword) {
        if (this.passwordHandler == null) {
            throw new IllegalStateException("PasswordHandler가 설정되지 않았습니다");
        }
        return passwordHandler.matches(rawPassword, this.userPswd);
    }
    
    /**
     * 비밀번호 변경 (기존 비밀번호 확인 후 변경)
     */
    public void changePassword(String oldPassword, String newPassword) {
        if (this.passwordHandler == null) {
            throw new IllegalStateException("PasswordHandler가 설정되지 않았습니다");
        }
        this.userPswd = passwordHandler.changePassword(this.userPswd, oldPassword, newPassword);
    }
    
    /**
     * 관리자용 비밀번호 재설정 (기존 비밀번호 확인 없이)
     */
    public void resetPassword(String newPassword) {
        if (this.passwordHandler == null) {
            throw new IllegalStateException("PasswordHandler가 설정되지 않았습니다");
        }
        this.userPswd = passwordHandler.encode(newPassword);
    }
    
    /**
     * 비밀번호 암호화 여부 확인
     */
    public boolean isPasswordEncoded() {
        if (this.passwordHandler == null) {
            throw new IllegalStateException("PasswordHandler가 설정되지 않았습니다");
        }
        return passwordHandler.isEncoded(this.userPswd);
    }
}